/* Autogenerated with kurento-module-creator */

#include "ExampleFilterOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace example
{

ExampleFilterOpenCVImpl::ExampleFilterOpenCVImpl ()
{
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
void ExampleFilterOpenCVImpl::process (cv::Mat &mat)
{
  cv::line(mat, cv::Point(20,20), cv::Point (100,100), cv::Scalar (255, 0, 0));
}


float ExampleFilterOpenCVImpl::getPropertyName ()
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "ExampleFilterOpenCVImpl::getpropertyName: Not implemented");
}

void ExampleFilterOpenCVImpl::setPropertyName (float propertyName)
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "ExampleFilterOpenCVImpl::setpropertyName: Not implemented");
}


void ExampleFilterOpenCVImpl::executeMethod (int paramName)
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "ExampleFilterOpenCVImpl::executeMethod: Not implemented");
}

} /* example */
} /* module */
} /* kurento */
