/* Autogenerated with kurento-module-creator */

#ifndef __EXAMPLE_FILTER_OPENCV_IMPL_HPP__
#define __EXAMPLE_FILTER_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "ExampleFilter.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace example
{

class ExampleFilterOpenCVImpl : public virtual OpenCVProcess
{

public:

  ExampleFilterOpenCVImpl ();

  virtual ~ExampleFilterOpenCVImpl () {};

  virtual void process (cv::Mat &mat);

  void executeMethod (int paramName);

  virtual float getPropertyName ();
  virtual void setPropertyName (float propertyName);
  sigc::signal<void, exampleEvent> signalexampleEvent;

};

} /* example */
} /* module */
} /* kurento */

#endif /*  __EXAMPLE_FILTER_OPENCV_IMPL_HPP__ */
