/* Autogenerated with kurento-module-creator */

#ifndef __EXAMPLE_FILTER_IMPL_HPP__
#define __EXAMPLE_FILTER_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "ExampleFilter.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "ExampleFilterOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace example
{
class ExampleFilterImpl;
} /* example */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::example::ExampleFilterImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace example
{

class ExampleFilterImpl : public OpenCVFilterImpl, public virtual ExampleFilter, public virtual ExampleFilterOpenCVImpl
{

public:

  ExampleFilterImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~ExampleFilterImpl () {};

  void executeMethod (int paramName);

  virtual float getPropertyName ();
  virtual void setPropertyName (float propertyName);

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* example */
} /* module */
} /* kurento */

#endif /*  __EXAMPLE_FILTER_IMPL_HPP__ */
